"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    app=['Command_Library.py'],
    data_files=['./images/search.png'],
    options=dict(
        py2app=dict(
            iconfile='Command_Library.icns',
            plist=dict(
                NSRequiresAquaSystemAppearance=False, CFBundleGetInfoString='Collect, save, and share your most used commands and snippets.',CFBundleIconFile='Command_Library.icns'))),
    setup_requires=['py2app'],
)

